# Generated by Django 6.0.7 on 2026-07-09 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('role', models.CharField(max_length=100)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('ip_address', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=100)),
                ('classification', models.CharField(choices=[('validation_not_malicious', 'Validation, not malicious'), ('important_ot_operation', 'Important OT operation'), ('suspicious_ot_operation', 'Suspicious OT operation')], max_length=64)),
                ('tag', models.CharField(max_length=100)),
                ('node_id', models.CharField(max_length=255)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('correlation_window_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at_from_case', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('rule_ids', models.JSONField(blank=True, default=list)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ('-created_at_from_case', '-ingested_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('classification_hint', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ('rule_id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('node_id', models.CharField(max_length=255, unique=True)),
                ('tag_type', models.CharField(max_length=100)),
                ('criticality', models.CharField(max_length=50)),
                ('station_or_area', models.CharField(blank=True, max_length=100)),
                ('is_writable', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EvidenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('rule_id', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('agent', models.CharField(blank=True, max_length=100)),
                ('location', models.TextField(blank=True)),
                ('evidence_type', models.CharField(blank=True, max_length=100)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_events', to='soc.case')),
            ],
            options={
                'ordering': ('timestamp', 'id'),
                'constraints': [models.UniqueConstraint(fields=('case', 'timestamp', 'rule_id', 'location'), name='unique_evidence_event_per_case')],
            },
        ),
    ]
